# Generated by Django 6.0.6 on 2026-06-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClaseKitesurf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ej: Curso Básico Inicial', max_length=100)),
                ('descripcion', models.TextField()),
                ('duracion_horas', models.IntegerField(help_text='Duración en horas')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
