# Generated by Django 6.0.6 on 2026-06-29 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clasekitesurf',
            options={'verbose_name': 'Clase de Kitesurf', 'verbose_name_plural': 'Clases de Kitesurf'},
        ),
        migrations.AddField(
            model_name='clasekitesurf',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='clases_fotos/', verbose_name='Foto del Curso'),
        ),
        migrations.AlterField(
            model_name='clasekitesurf',
            name='descripcion',
            field=models.TextField(verbose_name='La pasión por el kitesurf no se explica, se vive. En nuestra escuela, este deporte es parte de nuestra identidad familiar desde hace años. Diego, instructor con años de trayectoria, combina el conocimiento técnico profundo con la experiencia de quien ha dedicado su vida a entender el viento y el agua. No te enseñamos solo a navegar; te transmitimos el respeto por el mar, la seguridad necesaria para disfrutar cada sesión y la técnica precisa para progresar con confianza. Somos una familia apasionada compartiendo lo que amamos, con todo el equipamiento profesional necesario para que tu aprendizaje sea seguro, constante y, sobre todo, inolvidable.'),
        ),
        migrations.AlterField(
            model_name='clasekitesurf',
            name='duracion_horas',
            field=models.IntegerField(verbose_name='Duración 3 horas, 1:30 teorico/practiro y otra 1:30 pero todo practico  '),
        ),
        migrations.AlterField(
            model_name='clasekitesurf',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio 200.000'),
        ),
        migrations.AlterField(
            model_name='clasekitesurf',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Escuela de Entrenamiento Kitesurf'),
        ),
    ]
